### ISSUE TITLE
no logs in Kibana

### ISSUE THREAD

**Issue by mohamedhaleem** [sqshq/ELK-docker#1]
Hi 

i am trying to use your project to collect logs from our docker containers

I start the container as follows:

docker run -d -v /var/run/docker.sock:/tmp/docker.sock -e LOGSTASH_HOST=96.x.x.A -e LOGSTASH_PORT=5044 --name filebeat bargenson/filebeat

I can load up kibana UI but i can't see any logs .. so i tried the following from the machine running docker-filebeat:

nc -w1 96.x.x.A 5044 <<< "testing again from my home machine"

And the machine having the log stash forwarder, i see the following...

{:timestamp=>"2016-03-09T03:30:18.611000+0000", :message=>"Beats Input: Remote connection closed", :peer=>"96.x.x.B:58768", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: Lumberjack::Beats::Parser::UnsupportedProtocol, unsupported protocol 116>, :level=>:warn}

How to resolve this?

**Comment by sqshq** [comment]
Hi.

I think you should double-check your filebeat configuration and make sure that it's really sending stuff to logstash.

Your logstash log, caused by netcat request just saying that connection successful, but protocol is unsupported (beats use binary protocol to ship data).

Anyway, you can always curl manually all containers in this configuration and even ship logs directly to elasticsearch for test purposes.
